server:
  port: 8080

spring:
  application:
    name: team-quest
  datasource:
    url: jdbc:postgresql://localhost:5432/team_quest?currentSchema=tq
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        default_schema: tq
  liquibase:
    change-log: classpath:/db/changelog.yaml
    liquibase-schema: tq
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

file-storage:
  url:
#    root: http://localhost:${server.port}/api/v1/filestorage
    download: http://localhost:${server.port}/api/v1/filestorage/download
  file:
    bucket: /home/ulutkou/Projects/team-quest/app-files

#quest:
#  image:
#    bucket: users/:user/quests/images
#      enabled: true
#      location: classpath:/file_temp

#springdoc:
#  api-docs:
#    path: /v3/api-docs/
#    enabled: true
#  swagger-ui:
#    config-url: /swagger-ui.html
#    enabled: true
