spring:
  application:
    name: team-quest
  datasource:
    url: jdbc:postgresql://localhost:5432/team_quest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog.yaml


